<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Process;

/**
 * Run via: php artisan backup:run
 * Scheduled daily in bootstrap/app.php.
 *
 * Backs up (a) the full MySQL database via mysqldump and (b) uploaded
 * document originals + trained ML model artifacts — the two kinds of data
 * that cannot be regenerated by re-running migrations/seeders. Code and
 * config are already safe in git; this only covers runtime state, which
 * this project has already lost twice this session to out-of-band
 * database resets (see DatabaseSeeder's idempotency fix, and the ML model
 * having to be retrained after disappearing).
 *
 * Retention: keeps the newest N backups per type (config('backup.keep'),
 * default 14) and prunes older ones on every run, so this can run
 * unattended indefinitely without slowly filling the disk.
 *
 * Restore with: php artisan backup:restore {timestamp}
 */
class BackupSystem extends Command
{
    protected $signature = 'backup:run';
    protected $description = 'Back up the database and document/ML-model storage, pruning old backups.';

    public function handle(): int
    {
        $backupDir = storage_path('app/backups');
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
        }

        $timestamp = now()->format('Y-m-d_His');

        $dbOk = $this->backupDatabase($backupDir, $timestamp);
        $filesOk = $this->backupFiles($backupDir, $timestamp);

        $this->prune($backupDir);

        if ($dbOk && $filesOk) {
            $this->info("Backup complete: {$timestamp}");
            Log::info("Backup completed successfully: {$timestamp}");

            return self::SUCCESS;
        }

        $this->error('Backup finished with errors — check storage/logs/laravel.log');

        return self::FAILURE;
    }

    private function backupDatabase(string $backupDir, string $timestamp): bool
    {
        $dumpPath = "{$backupDir}/db_{$timestamp}.sql.gz";

        // Written to a temp --defaults-extra-file rather than passed as
        // -p<password> on the command line, which would otherwise be
        // visible to any other local user via `ps aux` for the process's
        // lifetime.
        $defaultsFile = tempnam(sys_get_temp_dir(), 'my-cnf-');
        file_put_contents($defaultsFile, sprintf(
            "[client]\nuser=%s\npassword=%s\nhost=%s\nport=%s\n",
            config('database.connections.mysql.username'),
            config('database.connections.mysql.password'),
            config('database.connections.mysql.host'),
            config('database.connections.mysql.port'),
        ));
        chmod($defaultsFile, 0600);

        try {
            $database = config('database.connections.mysql.database');
            $process = Process::fromShellCommandline(
                'mysqldump --defaults-extra-file=' . escapeshellarg($defaultsFile)
                . ' --single-transaction --routines --triggers '
                . escapeshellarg($database) . ' | gzip > ' . escapeshellarg($dumpPath)
            );
            $process->setTimeout(300);
            $process->run();

            if (!$process->isSuccessful()) {
                Log::error('Database backup failed: ' . $process->getErrorOutput());
                @unlink($dumpPath);

                return false;
            }

            return true;
        } finally {
            unlink($defaultsFile);
        }
    }

    private function backupFiles(string $backupDir, string $timestamp): bool
    {
        $archivePath = "{$backupDir}/files_{$timestamp}.tar.gz";
        $paths = array_values(array_filter([
            is_dir(storage_path('app/documents')) ? 'documents' : null,
            is_dir(storage_path('app/ml_models')) ? 'ml_models' : null,
            is_dir(storage_path('app/ml_datasets')) ? 'ml_datasets' : null,
        ]));

        if ($paths === []) {
            return true; // nothing uploaded/trained yet — not a failure
        }

        $process = new Process(array_merge(
            ['tar', '-czf', $archivePath, '-C', storage_path('app')],
            $paths
        ));
        $process->setTimeout(300);
        $process->run();

        if (!$process->isSuccessful()) {
            Log::error('File backup failed: ' . $process->getErrorOutput());
            @unlink($archivePath);

            return false;
        }

        return true;
    }

    private function prune(string $backupDir): void
    {
        $keep = (int) config('backup.keep', 14);

        foreach (['db_*.sql.gz', 'files_*.tar.gz'] as $pattern) {
            $files = glob("{$backupDir}/{$pattern}");
            sort($files); // filenames carry a sortable timestamp, oldest first
            $stale = array_slice($files, 0, max(0, count($files) - $keep));
            foreach ($stale as $file) {
                unlink($file);
            }
        }
    }
}
